### ISSUE TITLE
It's not working since the last Playstation update

### ISSUE THREAD

**Issue by GaborVilagos** [xeropresence/remoteplay-version-patcher#3]
Since two days ago, I can't connect to my PS5. I use PS Remote Play v5.5.0.08250 and so far it worked perfectly with the version patcher. But now, when I try to connect, it says that I must update to continue. I tried to use the version patcher again but with no success...

**Comment by element-40** [comment]
The same thing happened with mine, multiple times, but after closing it all and re-running it successfully patched it again.  Try rebooting your machine and patching before running remote play at all.

**Comment by element-40** [comment]
> Since two days ago, I can't connect to my PS5. I use PS Remote Play v5.5.0.08250 and so far it worked perfectly with the version patcher. But now, when I try to connect, it says that I must update to continue. I tried to use the version patcher again but with no success...

The same thing happened with mine, multiple times, but after closing it all and re-running it successfully patched it again. Try rebooting your machine and patching before running remote play at all.

**Comment by GaborVilagos** [comment]
> > Since two days ago, I can't connect to my PS5. I use PS Remote Play v5.5.0.08250 and so far it worked perfectly with the version patcher. But now, when I try to connect, it says that I must update to continue. I tried to use the version patcher again but with no success...
> 
> The same thing happened with mine, multiple times, but after closing it all and re-running it successfully patched it again. Try rebooting your machine and patching before running remote play at all.

Unfortunately, it didn't work. I rebooted my PC, then ran the version patcher as an administrator (twice, to make sure), and then ran Remote Play, and it still asks for an update.
I really hope to find a solution, because I'm a disabled gamer and can't play on my PS5 in any other way...

**Comment by xeropresence** [comment]
Can you screenshot the message your seeing? If you recently updated the playstation there may have been change at the actual protocol level that would prevent the old version from working even with it's version patched.

**Comment by xeropresence** [comment]
I'd also recommend looking at chiaki, specifically this fork that has more updates

https://github.com/streetpea/chiaki4deck/releases

**Comment by element-40** [comment]
> > > Since two days ago, I can't connect to my PS5. I use PS Remote Play v5.5.0.08250 and so far it worked perfectly with the version patcher. But now, when I try to connect, it says that I must update to continue. I tried to use the version patcher again but with no success...
> > 
> > 
> > The same thing happened with mine, multiple times, but after closing it all and re-running it successfully patched it again. Try rebooting your machine and patching before running remote play at all.
> 
> Unfortunately, it didn't work. I rebooted my PC, then ran the version patcher as an administrator (twice, to make sure), and then ran Remote Play, and it still asks for an update. I really hope to find a solution, because I'm a disabled gamer and can't play on my PS5 in any other way...

For me when I ran it it was saying it would patch 6.5xx to 6.5xx even though the current version for download is 7.0 (it was actually very 5.x but had been patched before so I think it saw the patched 6.5 and was reporting that as the version)

I found the url in the source code that is checking version and confirmed it still returned 7.0 when I hit the endpoint, so thats when I restarted it all and the next time I ran the tool, it said patching 6.5xx to 7.0 Have you checked if remote play launches on startup for some reason? Perhaps try to force quit the process from ctrl alt del?

**Comment by xeropresence** [comment]
I just reinstalled 5.5.0.08250 and ran the patcher and got these results
Patching file version from 5.5.0.8250 to 7.0.0.2070
Patching product version from 5.5.0.8250 to 7.0.0.2070
Patching complete, press any key to continue...

**Comment by GaborVilagos** [comment]
> I just reinstalled 5.5.0.08250 and ran the patcher and got these results Patching file version from 5.5.0.8250 to 7.0.0.2070 Patching product version from 5.5.0.8250 to 7.0.0.2070 Patching complete, press any key to continue...

It worked! Thanks!

**Comment by GaborVilagos** [comment]
> I just reinstalled 5.5.0.08250 and ran the patcher and got these results Patching file version from 5.5.0.8250 to 7.0.0.2070 Patching product version from 5.5.0.8250 to 7.0.0.2070 Patching complete, press any key to continue...



> I just reinstalled 5.5.0.08250 and ran the patcher and got these results Patching file version from 5.5.0.8250 to 7.0.0.2070 Patching product version from 5.5.0.8250 to 7.0.0.2070 Patching complete, press any key to continue...

It worked! Thanks!
